

Latex_tutorial.pdf:	Latex_tutorial.tex Latex_tutorial.bib
	pdflatex Latex_tutorial.tex
	bibtex Latex_tutorial.aux
	pdflatex Latex_tutorial.tex
	pdflatex Latex_tutorial.tex

clean:
	- rm Latex_tutorial.pdf Latex_tutorial.blg Latex_tutorial.out Latex_tutorial.bbl Latex_tutorial.aux 







